#!/usr/bin/env python3
"""Generate the make fragment that drives the portable (non-S32DS) build.

The S32DS/Eclipse project stays the single source of truth: this script derives
the source list, the compiler flags, the assembler flags and the link line *from
the CDT-generated files* of a configuration, so the two build systems cannot
drift apart.

Inputs, all under <repo>/<CONFIG>/ (all generated by S32DS):

    sources.mk                                        -> SUBDIRS
    <subdir>/subdir.mk                                -> C_SRCS / S_SRCS
    src/main.args                                     -> C compiler flags
    Project_Settings/Startup_Code/Vector_Table.args   -> assembler flags
    BMS_demo.args                                     -> link flags, object list
                                                         (in link order), libraries

Output: a make fragment defining C_SRCS, S_SRCS, CFLAGS, ASFLAGS, LDFLAGS_OPT,
LINK_OBJS and LDFLAGS_LIB.

Flag text is migrated verbatim; exactly three kinds of token are rewritten:

  * the four SDK include roots, now resolved from the vendored sdk/ tree via
    $(SDK_BASE) / $(SDK_PLATFORM);
  * repository-relative include paths, which become $(REPO)-anchored because the
    compiler no longer runs with the configuration directory as its cwd;
  * the linker script (-> $(LDFLAGS_LD), see below) and the map file (-> $(OUT)).

`--sysroot` is dropped: it points into the Windows S32DS installation. Set
SYSROOT on the make command line if the toolchain in use needs one.

Any other token that still looks like a Windows absolute path is a hard error,
as is a mismatch between the linked objects and the objects implied by the
source lists.

Usage:
    python make/gen_sources.py --repo <abs repo> --config Debug_FLASH --out <file>
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

# Which link response file each configuration must use. Drift here means the
# CDT project and this build disagree about the memory layout: fail, don't guess.
EXPECTED_LDSCRIPT = {
    "Debug_FLASH": "linker_flash_s32k344.ld",
    "Release_RAM": "linker_ram_s32k344.ld",
}

# "-x assembler-with-cpp" arrives as two tokens; "-std=c99" as one.
ASM_MARKER = "assembler-with-cpp"
C_MARKER = "-std=c99"

# SDK include roots inside the CDT response files -> vendored replacements.
# Longest key first so "startup/include" is never matched by "include".
SDK_INCLUDE_MAP = (
    ("Platform_TS_T40D34M70I1R0/startup/include", "$(SDK_PLATFORM)/startup/include"),
    ("BaseNXP_TS_T40D34M70I1R0/header", "$(SDK_BASE)/header"),
    ("BaseNXP_TS_T40D34M70I1R0/include", "$(SDK_BASE)/include"),
    ("Platform_TS_T40D34M70I1R0/include", "$(SDK_PLATFORM)/include"),
)

WINDOWS_ABS_RE = re.compile(r"^[A-Za-z]:[/\\]")
ASSIGN_RE = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*(\+=|:=|\?=|=)\s*(.*)$")


class GenError(Exception):
    """Condition that must stop the build: bad, missing or drifted CDT metadata."""


def fail(message: str) -> None:
    raise GenError(message)


# --------------------------------------------------------------------------- #
# Response file parsing
# --------------------------------------------------------------------------- #
def tokenize_rsp(text: str) -> list[str]:
    """Split a GCC response file / CDT .args file into tokens.

    Not a whitespace split: double and single quotes are honoured, a backslash
    before a newline continues the line, and a backslash is otherwise literal so
    that Windows paths such as C:\\NXP\\... survive intact.
    """
    tokens: list[str] = []
    current: list[str] = []
    quote: str | None = None
    started = False
    i, n = 0, len(text)

    while i < n:
        ch = text[i]

        if quote is None and ch == "\\":
            nxt = text[i + 1] if i + 1 < n else ""
            if nxt in ("\r", "\n"):                      # line continuation
                i += 2
                if i < n and text[i] == "\n":
                    i += 1
                continue
            if nxt in ('"', "'", "\\", " ", "\t"):        # escaped literal
                current.append(nxt)
                started = True
                i += 2
                continue
            current.append(ch)                           # literal backslash
            started = True
            i += 1
            continue

        if quote is None and ch in "\"'":
            quote = ch
            started = True
            i += 1
            continue

        if quote is not None and ch == quote:
            quote = None
            i += 1
            continue

        if quote is None and ch in " \t\r\n":
            if started:
                tokens.append("".join(current))
                current = []
                started = False
            i += 1
            continue

        current.append(ch)
        started = True
        i += 1

    if quote is not None:
        fail("unterminated quote in a response file")
    if started:
        tokens.append("".join(current))
    return tokens


def read_rsp(path: Path) -> list[str]:
    if not path.is_file():
        fail(f"expected CDT response file is missing: {path}")
    return tokenize_rsp(path.read_text(encoding="utf-8", errors="replace"))


def parse_make_assignment(text: str, name: str) -> list[str]:
    """Values assigned to NAME (=, :=, += or ?=), honouring continuations."""
    values: list[str] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        match = ASSIGN_RE.match(lines[i])
        if match and match.group(1) == name:
            chunk = [match.group(3)]
            while chunk[-1].rstrip().endswith("\\"):
                chunk[-1] = chunk[-1].rstrip()[:-1]
                i += 1
                if i >= len(lines):
                    break
                chunk.append(lines[i])
            for item in chunk:
                item = item.strip()
                if item:
                    values.append(item)
        i += 1
    return values


# --------------------------------------------------------------------------- #
# Path handling
# --------------------------------------------------------------------------- #
def repo_relative(value: str, config_dir: Path, repo: Path, what: str, kind: str = "file") -> str:
    """Resolve a CDT path (e.g. ../src/main.c) to a POSIX repo-relative path."""
    target = Path(os.path.normpath(os.path.join(str(config_dir), value.replace("\\", "/"))))
    rel = os.path.relpath(str(target), str(repo))
    if rel == os.pardir or rel.startswith(os.pardir + os.sep):
        fail(f"{what}: '{value}' resolves outside the repository ({target})")
    existing = target.is_file() if kind == "file" else target.is_dir()
    if not existing:
        fail(f"{what}: '{value}' does not exist ({target})")
    return Path(rel).as_posix()


def check_paths(repo: Path, out: Path) -> None:
    """Source and object paths are used as make prerequisites, so they must not
    contain whitespace: make would split them and the build would fall apart in
    confusing ways. Fail early with an explanation instead."""
    for label, path in (("repository", repo), ("output", out)):
        if any(ch.isspace() for ch in str(path)):
            fail(
                f"the {label} path contains whitespace ('{path}'). The portable build "
                "uses these paths as make prerequisites, which cannot be quoted - "
                "build from a path without spaces"
            )


def check_sdk(repo: Path) -> None:
    """The four vendored include roots must be present before anything is derived."""
    required = [
        "base/header",
        "base/include",
        "platform/include",
        "platform/startup/include",
    ]
    missing = [name for name in required if not (repo / "sdk" / name).is_dir()]
    if missing:
        fail(
            "vendored SDK headers are missing: "
            + ", ".join(f"sdk/{name}" for name in missing)
            + " - run 'make vendor-sdk S32DS_SDK_ROOT=<...>/PlatformSDK_S32K3/RTD'"
        )


def rewrite_flag(token: str, what: str) -> str | None:
    """Rewrite one compiler/linker flag. Returns None if it must be dropped."""
    if token.startswith("--sysroot="):
        return None                       # points into the Windows S32DS install

    if token.startswith("-I") and len(token) > 2:
        pathspec = token[2:]
        for needle, replacement in SDK_INCLUDE_MAP:
            if needle in pathspec.replace("\\", "/"):
                return f'-I"{replacement}"'
        if not pathspec.startswith("$("):
            return '-I"$(REPO)/' + repo_relative(
                pathspec, CONFIG_DIR, REPO, what, kind="dir"
            ) + '"'

    if WINDOWS_ABS_RE.match(token):
        fail(f"{what}: unhandled Windows absolute path in '{token}'")
    return token


# --------------------------------------------------------------------------- #
# Flag set assembly
# --------------------------------------------------------------------------- #
def c_flags(config_dir: Path, repo: Path) -> str:
    """The C compiler flags, verified identical in every folder of the config."""
    canonical_path = config_dir / "src" / "main.args"
    canonical = read_rsp(canonical_path)
    if C_MARKER not in canonical:
        fail(f"{canonical} is not a C compiler response file")

    for argfile in sorted(config_dir.rglob("*.args")):
        if argfile == config_dir / "BMS_demo.args" or argfile == canonical_path:
            continue
        tokens = read_rsp(argfile)
        if ASM_MARKER in tokens:
            continue
        if tokens != canonical:
            fail(
                f"{argfile.relative_to(repo)} has a different flag set than "
                f"{canonical_path.relative_to(repo)}; the portable build assumes one "
                "flag set per configuration - reconcile the S32DS folder settings"
            )
    return render_flags(canonical, "C flags")


def asm_flags(config_dir: Path, repo: Path) -> str:
    """The assembler flags, verified identical in both startup .args files."""
    canonical_path = config_dir / "Project_Settings" / "Startup_Code" / "Vector_Table.args"
    canonical = read_rsp(canonical_path)
    if ASM_MARKER not in canonical:
        fail(f"{canonical_path} is not an assembler response file")

    for argfile in sorted(config_dir.rglob("*.args")):
        if ASM_MARKER not in read_rsp(argfile):
            continue
        if argfile == canonical_path:
            continue
        if read_rsp(argfile) != canonical:
            fail(
                f"{argfile.relative_to(repo)} has a different flag set than "
                f"{canonical_path.relative_to(repo)}; the portable build assumes one "
                "assembler flag set per configuration"
            )
    return render_flags(canonical, "assembler flags")


def render_flags(tokens: list[str], what: str) -> str:
    rendered = [rewrite_flag(token, what) for token in tokens]
    return " ".join(tok for tok in rendered if tok is not None) + " $(SYSROOT_FLAG)"


def link_parts(config_dir: Path, repo: Path, config: str) -> tuple[str, list[str], str]:
    """Split BMS_demo.args into (option flags, objects in link order, libraries)."""
    what = "link flags"
    tokens = read_rsp(config_dir / "BMS_demo.args")

    expected_ld = EXPECTED_LDSCRIPT.get(config)
    if expected_ld is None:
        fail(f"no linker script mapping known for configuration '{config}'")
    ld_path = repo / "Project_Settings" / "Linker_Files" / expected_ld
    if not ld_path.is_file():
        fail(f"linker script referenced for {config} does not exist: {ld_path}")

    options: list[str] = []
    objects: list[str] = []
    libraries: list[str] = []
    seen_object = False
    i = 0
    while i < len(tokens):
        token = tokens[i]

        if token == "-T":
            if i + 1 >= len(tokens):
                fail(f"{what}: '-T' without a linker script")
            script = Path(tokens[i + 1].replace("\\", "/"))
            if script.name != expected_ld:
                fail(
                    f"{what}: {config} links with '{script.name}' but the portable "
                    f"build expects '{expected_ld}'"
                )
            options += ["-T", '"$(LDFILE)"']
            i += 2
            continue

        if token.startswith("-Wl,-Map,"):
            options.append('-Wl,-Map,"$(MAP)"')
            i += 1
            continue

        if token.startswith("-l"):
            libraries.append(token)
            i += 1
            continue

        if token.endswith(".o") and not token.startswith("-"):
            seen_object = True
            objects.append(link_object(token, config_dir, what))
            i += 1
            continue

        if seen_object:
            fail(f"{what}: '{token}' appears after the object list; the portable build "
                 "would reorder it - check the S32DS link order")
        rewritten = rewrite_flag(token, what)
        if rewritten is not None:
            options.append(rewritten)
        i += 1

    if not objects:
        fail(f"{what}: no object files found in {config_dir / 'BMS_demo.args'}")
    return " ".join(options) + " $(SYSROOT_FLAG)", objects, " ".join(libraries)


# --------------------------------------------------------------------------- #
# Source list
# --------------------------------------------------------------------------- #
def source_lists(config_dir: Path, repo: Path) -> tuple[list[str], list[str]]:
    sources_mk = config_dir / "sources.mk"
    if not sources_mk.is_file():
        fail(f"missing {sources_mk} - is '{config_dir.name}' a real S32DS configuration?")
    subdirs = parse_make_assignment(sources_mk.read_text(encoding="utf-8"), "SUBDIRS")
    if not subdirs:
        fail(f"no SUBDIRS found in {sources_mk}")

    c_sources: list[str] = []
    s_sources: list[str] = []
    for subdir in subdirs:
        subdir_mk = config_dir / subdir / "subdir.mk"
        if not subdir_mk.is_file():
            fail(f"missing per-folder makefile: {subdir_mk}")
        text = subdir_mk.read_text(encoding="utf-8")
        for value in parse_make_assignment(text, "C_SRCS"):
            c_sources.append(repo_relative(value, config_dir, repo, f"{subdir}/subdir.mk C_SRCS"))
        for value in parse_make_assignment(text, "S_SRCS"):
            s_sources.append(repo_relative(value, config_dir, repo, f"{subdir}/subdir.mk S_SRCS"))

    if not c_sources:
        fail(f"no C sources found for {config_dir.name}")
    return c_sources, s_sources


def link_object(value: str, config_dir: Path, what: str) -> str:
    """Normalise a linked object path to its source-relative form.

    CDT records objects relative to the configuration directory (./src/main.o);
    the portable build keys every object by the path of the source it comes from
    (src/main.o -> $(OUT)/obj/src/main.o). Objects are deliberately not checked
    for existence: a configuration that has never been built by S32DS still has
    a link response file.
    """
    rel = value.replace("\\", "/")
    while rel.startswith("./"):
        rel = rel[2:]
    prefix = config_dir.name + "/"
    if rel.startswith(prefix):
        rel = rel[len(prefix):]
    if not rel or rel.startswith("../") or WINDOWS_ABS_RE.match(rel) or Path(rel).is_absolute():
        fail(f"{what}: unexpected object path '{value}'")
    return rel


def check_objects(c_sources: list[str], s_sources: list[str], link_objs: list[str]) -> None:
    """The linked objects and the objects implied by the sources must agree exactly."""
    derived = [src[: -len(Path(src).suffix)] + ".o" for src in c_sources + s_sources]

    for label, items in (("C/S sources", derived), ("link line", link_objs)):
        duplicates = sorted({item for item in items if items.count(item) > 1})
        if duplicates:
            fail(f"duplicate objects in the {label}: {', '.join(duplicates)}")

    missing = sorted(set(derived) - set(link_objs))
    extra = sorted(set(link_objs) - set(derived))
    if missing or extra:
        details = []
        if missing:
            details.append(f"built from source but never linked: {', '.join(missing)}")
        if extra:
            details.append(f"linked but has no source in SUBDIRS: {', '.join(extra)}")
        fail(
            f"object list mismatch ({len(derived)} from sources vs {len(link_objs)} linked). "
            + "; ".join(details)
        )
    if len(derived) != len(link_objs):
        fail(f"object count mismatch: {len(derived)} from sources, {len(link_objs)} linked")


# --------------------------------------------------------------------------- #
# Fragment emission
# --------------------------------------------------------------------------- #
def make_list(variable: str, values: list[str], prefix: str = "", quote: bool = False) -> str:
    def render_value(value: str) -> str:
        return f'"{prefix}{value}"' if quote else f"{prefix}{value}"

    body = " \\\n".join(render_value(value) for value in values)
    return f"{variable} := \\\n{body}\n\n"


def render(
    config: str,
    c_sources: list[str],
    s_sources: list[str],
    cflags: str,
    asflags: str,
    ld_options: str,
    link_objs: list[str],
    libraries: str,
) -> str:
    out = [
        "# Generated by make/gen_sources.py from the S32DS configuration files.\n",
        "# Do not edit: run 'make check-toolchain' / build again to regenerate.\n",
        f"# Configuration: {config}\n",
        "\n",
    ]
    out.append(f"CFLAGS := {cflags}\n\n")
    out.append(f"ASFLAGS := {asflags}\n\n")
    out.append(f"LDFLAGS_OPT := {ld_options}\n\n")
    out.append(f"LDFLAGS_LIB := {libraries}\n\n")
    out.append(make_list("C_SRCS", c_sources, "$(REPO)/"))
    out.append(make_list("S_SRCS", s_sources, "$(REPO)/"))
    # Not quoted: these are make prerequisites as well as linker arguments, and
    # make takes quoted words literally. Paths containing spaces are rejected
    # up front instead (see check_paths).
    out.append(make_list("LINK_OBJS", link_objs, "$(OUT)/obj/"))
    return "".join(out)


def write_if_changed(path: Path, content: str) -> bool:
    """Write only when the content differs, so make does not restart needlessly."""
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main(argv: list[str]) -> int:
    global CONFIG_DIR, REPO

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--repo", required=True, help="absolute path of the repository root")
    parser.add_argument("--config", required=True, help="S32DS configuration name")
    parser.add_argument("--out", required=True, help="make fragment to write")
    parser.add_argument("-q", "--quiet", action="store_true")
    args = parser.parse_args(argv)

    REPO = Path(args.repo).absolute()
    CONFIG_DIR = REPO / args.config

    try:
        if not CONFIG_DIR.is_dir():
            fail(f"configuration directory does not exist: {CONFIG_DIR}")
        check_paths(REPO, Path(args.out).absolute())
        check_sdk(REPO)
        c_sources, s_sources = source_lists(CONFIG_DIR, REPO)
        flags_c = c_flags(CONFIG_DIR, REPO)
        flags_asm = asm_flags(CONFIG_DIR, REPO)
        ld_options, link_objs, libraries = link_parts(CONFIG_DIR, REPO, args.config)
        check_objects(c_sources, s_sources, link_objs)
        content = render(
            args.config, c_sources, s_sources, flags_c, flags_asm, ld_options, link_objs, libraries
        )
        changed = write_if_changed(Path(args.out), content)
    except GenError as exc:
        print(f"gen_sources.py: error: {exc}", file=sys.stderr)
        return 1

    if not args.quiet:
        state = "updated" if changed else "unchanged"
        print(
            f"gen_sources.py: {args.config}: {len(c_sources)} C + {len(s_sources)} asm sources, "
            f"{len(link_objs)} objects linked ({state})"
        )
    return 0


CONFIG_DIR = Path()
REPO = Path()

if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
